Create header and main for mobile view
Allenkeys/portfolio pull request #1
Opened 2022-08-19 23:24 UTC by Allenkeys

2022-08-19 23:44 UTC, MaganaAsiati reviewed
# Hi @Allenkeys 

made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:
- [ ] Please follow this [README.md template](https://github.com/microverseinc/readme-template/blob/master/README.md). This will make your repository be more professional.
 - [ ] Pull Request should have a descriptive title telling you what changes are inside. This is necessary to make it more readable when you revisit your previous commits.
 - [ ] Pull Request should have a short summary describing introduced changes in more detail. This is necessary to make it more readable when you revisit your previous commits.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
Cheers and Happy coding!👏👏👏
--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-08-20 09:21 UTC, Allenkeys commented
Hi @MaganaAsiati 
I do not seem to understand what changes is required of me. Please do well to help my understanding.

2022-08-20 09:33 UTC, MaganaAsiati commented
I called you on Zoom but you are not available

2022-08-20 09:35 UTC, Allenkeys commented
@MaganaAsiati  How do I join the zoom call? From Dashboard?

2022-08-20 10:07 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

## Hi @Allenkeys 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![121369265-4e418880-c901-11eb-848c-1eff06d5a4cf](https://user-images.githubusercontent.com/95297251/185740804-0e17ebe5-2650-469e-bc2f-50da62ea32f9.gif)



## Highlights
✅ No linter error
✅ README is professional
✅Correct use of GitFlow heavy_check_mark

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] I would suggest you use good commit messages since their very descriptive while tracking the changes in your project grin
- [ ]  Kindly make your pull request more descriptive to let us know what you implemented in the current branch, her bellow an example of a descriptive pull request :grinning: 
![image](https://user-images.githubusercontent.com/95297251/185740586-22dc7356-39fc-42d4-9194-b3b6de5fe419.png)

- [ ] kindly make sure the content of your all page has the max of 100% so that it will contain all screens and remove the scrolling button, check below the responsiveness of your page compare to the Figma design

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
Cheers and Happy coding!👏👏👏

2022-08-20 10:07 UTC, MaganaAsiati commented on index.html
> +    </header>
- [ ] Kindly make sure your :100: 
   1. The logo has a link (`a` tag).:grinning: 
    2. The hamburger button has a `nav` tag. :grinning: 
Here bellows an example of how it should be supposed to look :grinning: 
```
<header class="logo">
    <a class="logo" href="#">{da<span>Gray}_</a>
    <nav class="nav_menu">
      <img src="./images/menu.png" alt="menu"> 
    </nav>
</header>
```

This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-08-20 10:07 UTC, MaganaAsiati commented on index.css
> +  padding: 114px 24px 138px 24px;
- [ ] You did great by adding the padding (top, bottom, left, right) as defined in the design but it should be better to reduce the padding-top `padding: 80px 24px 138px 24px;` so that your icons will be more visible in your page and will not be cut like it show in your design. :grinning: :grinning: :grinning: 
## your design
![image](https://user-images.githubusercontent.com/95297251/185739898-e566dbc1-87cd-41a2-8220-a5c64e768460.png)
## Figma design 
![image](https://user-images.githubusercontent.com/95297251/185739974-2811bde3-6d6d-4c04-81ec-f66cef08d517.png)

2022-08-20 11:15 UTC, emmiiorji approved these changes
Hi @Allenkeys , 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- You have implemented the requested changes
- Good commit messages
- Good use of GitHub flow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 11:15 UTC, emmiiorji commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
_[Optional]_ I suggest that you remove this note from the README file. It's only a note to you (the author) not to your audience. By doing so, your documentation will be more professional and concise.

2022-08-20 11:21 UTC, merged